### PR TITLE
Add country support

### LINKED ISSUE #3: Doesn't support localization (country)
For instance, if you have a Danish browser, then per default, the country is set to "Denmark". This causes the phone and zip code validation to be Danish too, which fails the whole process.

For this reason, I think it's important to explicitly make it select the proper country from the dropdown box. And even let me specify which country I want.

### LINKED ISSUE #4: Does not validate account
It asks for information about the company's leaders, and hangs on that last page. When I poll the account though, it is indeed validated.

image

### PR DESCRIPTION
**Pull request by ffMathy**
Fixes #3 and fixes #4.

Turns out the final step of the verification process in #4 was due to the country in the browser being Danish, which apparently has some additional page.

### CODE REVIEW

**Comment by ffMathy** [comment]
I also verified that all tests pass.

**Comment by ffMathy** [comment]
@kgajera any chance you can approve the workflow for this one, so it'll run?

**Comment by ffMathy** [comment]
Can you approve again? I reformatted the code with prettier now.

**Comment by ffMathy** [comment]
@kgajera I think the test is failing on the build server because builds for pull requests don't include secrets per default.

If you can go in and click "retry" for the job, then it should succeed. That implies that the secrets will be included.

**Comment by ffMathy** [comment]
I confirmed this now.

You can see the test passes here with my own Stripe secret:
https://github.com/sponsorkit/stripe-onboarder/actions/runs/3525843395/jobs/5913053057

So you just need to retry the build @kgajera.

**Comment by ffMathy** [comment]
@kgajera let me know what you need for me to push this out. Currently the onboarder doesn't work at all for non-English computers.

**Review by kgajera — APPROVED** [review]

**Comment by kgajera** [comment]
> @kgajera let me know what you need for me to push this out. Currently the onboarder doesn't work at all for non-English computers.

I just published the new version @ffMathy, thank you!

**Pull request merged**
