### PR TITLE
Major rewrite and stability improvements

### PR DESCRIPTION
**Pull request by ffMathy**
This is a major rewrite of the whole library.

When I tried using it more widely, I noticed a couple of things that were not ideal (may have been at some point, but not anymore):
1. If a selector was not found, it was silently ignored.
2. The flows for `non_profit`, `business` and `individual` was reusing the same code. This made it difficult to see if a change broke something, or which selectors were needed, and which ones were not.
3. Other countries simply didn't work. For instance, `"DK"`.
4. The tests that were made were fine, but they did not test all combinations of possible values, which could all lead to varying Stripe forms.
5. Performance was less than ideal, since there was a lot of unnecessary `waitForSelector` calls. They also did not have any timeout, so would never fail.
6. Tests took a long time to run, because they were not run in parallel, and since a lot of the waiting time involved was verifying if an account was activated at the end.
7. If a test failed, it was hard to determine why, and actually fix the problem easily. It was also difficult to see what parameters were given to the failing test.
8. The browser language was set to the local machine's language, potentially creating variations in test results when running tests locally.
9. The code would sometimes think it was further ahead or further back, depending on whether or not there were validation errors or various factors that would complicate the flow. This in turn made it even harder to debug the root cause.

Here's what this pull request improves:
1. Selectors are no longer silently ignored if not found. They will throw an error instead. In the event where there is a selector that isn't always there, it has been explicitly checked for instead, and documented with a comment.
2. The flows for `non_profit`, `business` and `individual` now have their own individual files, with individual functions (one for each "page"). These individual page functions then call common atomic functions (like filling out an email address field) for having reusability while still making everything highly maintainable.
3. Other countries like "DK" now work.
4. The tests are now based on matrix testing. This defines a test automatically for every possible combination of input values. This means we can safely try something out and make sure it works everywhere.
5. We no longer wait for selectors, except in between page loads.
6. Tests are now parallel (up to 32 tests at once). In addition, since Stripe only allows to create 5 accounts per second (and one account is needed per test), there is a semaphore that makes sure only 3 accounts are created per second at maximum before each flow continues.
7. Now if a test fails, it triggers an `alert` in the browser window of the test, saying what the error is. In addition, it also doesn't close the browser window afterwards, so it gives you time to actually fix the problem in non-headless mode.
8. The browser's language is now always set to English (US).
9. Between each page, it is checked whether or not there are validation errors on the page. If there are, errors are thrown accordingly (with a meaningful description from Stripe about what is missing).

Let me know what you think!

Since I need this, I'll also host it over at github.com/sponsorkit/stripe-onboarder if this doesn't get merged.

### CODE REVIEW

**Comment by ffMathy** [comment]
@kgajera this is ready for review now! Read the description and let me know what you think!

**Comment by kgajera** [comment]
> @kgajera this is ready for review now! Read the description and let me know what you think!

Amazing work! Give me a day to do some testing.

**Comment by ffMathy** [comment]
@kgajera hmm it seems it won't work in Headless mode. Have you encountered that before? Pretty sure it also happened in the old version. But any idea of what could be wrong?

**Comment by ffMathy** [comment]
@kgajera by the way, I was thinking... If you trust me and my judgement, I could also be made an official contributor on this?

**Comment by ffMathy** [comment]
@kgajera oh, and I made tests pass now. So if you rerun them, they should work! This PR is fully ready to merge IMO.

**Comment by ffMathy** [comment]
Here is proof that it passes: https://github.com/sponsorkit/stripe-onboarder/actions/runs/3734125153/jobs/6335793355

**Comment by ffMathy** [comment]
Sorry @kgajera, closing this. I have to make a fork now and just maintain that instead. It's been a pleasure working on the library, but I can't wait anymore for an official merge.

**Pull request closed without merging**
